name: xpath_for_html
description: xpath package for HTML, most XPath syntax is supported.
version: 1.0.0
homepage: https://github.com/simonkimi/xpath_for_html

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  expressions: ^0.2.3
  html: ^0.15.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
